name: fire_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.1
  cloud_firestore: ^6.1.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  location: ^7.0.1
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  permission_handler: ^12.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google.png

# ğŸ”¥ ConfiguraÃ§Ã£o para gerar Ã­cone do app
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
